---
kind: pipeline
name: "Test ndsampler in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    image: python:3.6
    commands:
      - pip install pip -U
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.3.0#egg=kwarray
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.3.0#egg=kwimage
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.3.0#egg=kwplot
      - pip install -r requirements.txt -U
      - pip install -e .
      - ./run_tests.py

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh


---
kind: pipeline
name: "Test ndsampler in 2.7"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 2.7"
    image: python:2.7
    commands:
      - pip install pip -U
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.3.0#egg=kwarray
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.3.0#egg=kwimage
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.3.0#egg=kwplot
      - pip install -r requirements.txt -U
      - pip install -e .
      - ./run_tests.py

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh
