---
kind: pipeline
name: "Test ndsampler in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    #image: continuumio/miniconda3
    image: erotemic/research:PY_VER_3.6
    #image: python:3.6
    commands:
      - . $HOME/.local/conda/etc/profile.d/conda.sh
      - conda activate py3.6
      #- conda create -y -n py36 python=3.6
      #- conda activate py36
      #- conda install gdal -y
      - pip uninstall scikit-image -y
      - conda install scikit-image  -y
      - pip install pip -U
      - pip install scikit-build cmake numpy cython ninja ubelt cffi wheel setuptools
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.4.0#egg=kwarray --no-use-pep517
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.4.0#egg=kwimage --no-use-pep517
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwplot.git@dev/0.4.0#egg=kwplot --no-use-pep517
      - pip install -r requirements.txt
      - pip install . --no-use-pep517
      - ./run_tests.py

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh

---
kind: pipeline
name: "Test in 2.7"

platform:
  os: linux
  arch: amd64
  
steps:
  - name: "Test python 2.x"
    #image: python:2.7 
    #image: continuumio/miniconda2
    image: erotemic/research:PY_VER_2.7
    commands:
      - . $HOME/.local/conda/etc/profile.d/conda.sh
      - conda activate py2.7
      #- conda create -y -n py27 python=2.7
      #- conda activate py27
      #- conda install gdal -y
      - pip install pip -U
      - pip install scikit-build cmake numpy cython ninja ubelt cffi wheel setuptools
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.4.0#egg=kwarray --no-use-pep517
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.4.0#egg=kwimage --no-use-pep517
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwplot.git@dev/0.4.0#egg=kwplot --no-use-pep517
      - pip install -r requirements.txt
      - pip install . --no-use-pep517
      - ./run_tests.py

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh

